title: "迷い道の独り言/Ramblings from Astray"
author: "迷い"
description: "Gamedev diary! Probably..." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "example@mail.com"
#twitter_username: "twitteruser"
github_username: "mayoisugi"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
#remote_theme: mayoisugi/moonwalk
#jekyll-theme-console
#theme: minima
remote_theme: jekyll/minima

#baseurl: /blog
baseurl: 
url: https://mayoisugi.github.io

minima:
  skin: dark
  
style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: false # false (default) or true

lang: en 
languages: ["en", "jp"] 
permalink: /:categories/:year/:month/:day/:title/

rss: rss

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  
kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
